"""rename sos_posts/sos_comments to code_clinic_posts/code_clinic_comments

Revision ID: 26734e01ecea
Revises: aa366d538fd6
Create Date: 2026-08-27 13:33:53.269586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26734e01ecea'
down_revision = 'aa366d538fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_clinic_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_clinic_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_clinic_post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['code_clinic_post_id'], ['code_clinic_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sos_comments')
    op.drop_table('sos_posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sos_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('media_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sos_posts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sos_posts_pkey'))
    )
    op.create_table('sos_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sos_post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sos_post_id'], ['sos_posts.id'], name=op.f('sos_comments_sos_post_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sos_comments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sos_comments_pkey'))
    )
    op.drop_table('code_clinic_comments')
    op.drop_table('code_clinic_posts')
    # ### end Alembic commands ###
