"""Remove donations table (M-Pesa dropped)

Revision ID: 3334047076a6
Revises: f53cd0497247
Create Date: 2026-08-23 19:02:49.293678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3334047076a6'
down_revision = 'f53cd0497247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_checkout_request_id'))

    op.drop_table('donations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('donor_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('donor_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('merchant_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('checkout_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mpesa_receipt_number', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('result_desc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['donor_user_id'], ['users.id'], name=op.f('donations_donor_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('donations_pkey'))
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_checkout_request_id'), ['checkout_request_id'], unique=True)

    # ### end Alembic commands ###
